
FROM golang:1.19 AS builder
WORKDIR /app

COPY . .

ENV GO111MODULE=off

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o main .

FROM gcr.io/distroless/static-debian11

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["/main"]