FROM golang:1.19 AS builder
WORKDIR /app
COPY . .
RUN go mod init app && go mod tidy
RUN go build -o main .

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]