FROM golang:1.19 AS builder

WORKDIR /app

COPY . .

RUN go mod init app && go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM gcr.io/distroless/static-debian11
COPY --from=builder /app/main .

CMD ["/main"]